GET http://localhost:8080/books
Accept: application/json

###

POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "Clean Architeture",
    "author": "Robert C. Martin",
    "genre": "Software Engineering"
}

###

GET http://localhost:8080/books/1
Accept: application/json

###

PUT http://localhost:8080/books/1
Content-Type: application/json

{
    "title": "Clean Code",
    "author": "Robert C. Martin",
    "genre": "Software Development"
}

###

DELETE http://localhost:8080/books/1

###

GET http://localhost:8080/books-by-name/clean
Accept: application/json

###

POST http://localhost:8080/simulate
Accept: application/json

{
    "book_ids": [1, 2, 3]
}